### ISSUE TITLE
ListView can't work.

### ISSUE THREAD

**Issue by dyncan** [rajnikantroy/SalesforceSimplified#2]
When I click a listview link for a object, Can't redirect to a specific listview.

**Comment by rajnikantroy** [comment]
Hi @dyncan ,

Thanks for raising this issue, I really appreciate that you logged another issue.
You will get resolution for this issue on next update.

Please feel free to raise another issue if you found to make Salesforce Simplified Better.

Thanks!
Rajni Kant Roy

**Comment by rajnikantroy** [comment]
Hi @dyncan,

I am sorry to inform you that we cannot redirect to specific listview.

**Background for this implementation**
To redirect to any specific listview we need to create specific URL
https://ap8.salesforce.com/001?fcf=00B0o00000BGabZ is combination of 3 part
1. Base URL: https://ap8.salesforce.com
2. sObject Prefix: 001
3. ListView ID: 00B0o00000BGabZ

To show ListView, Simplified query on **Listview API** by below query
SELECT Id, DeveloperName, SobjectType, LastModifiedBy.name, NamespacePrefix FROM ListView

Listview API provide these fields **Id, Name, DeveloperName, NamespacePrefix, SobjectType, IsSoqlCompatible, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, LastReferencedDate** 

As we can see, we are not getting sObjectType ID to create above URL to redirect to any specific Listview.

Please raise another issues too, if that's implementable. I will provide you as new version of Salesforce Simplified.

Thanks!
Rajni Kant Roy
[Linkedin](https://www.linkedin.com/in/rajnikantroy/) | [Facebook](https://www.facebook.com/salesforcesimplified)

**Comment by dyncan** [comment]
Hi rajnikantroy,

Thank you for your reply and detailed explanation, 

According to the field information of the listview object you provided, I think it can be achieved as follows:

1. get sobject prefix by SobjectType field:

    ```
      /* SobjectType = 'Account'; */
      schema.sObjectType sObjType = Schema.getGlobalDescribe().get(SobjectType);
      sObjType.getDescribe().getKeyPrefix();
2. For now, we have base url, object prefix and listview id, so we can splice url like this:
   final URL:  baseURL + prefix+listviewID, 
   e.g. :  _https://ap8.salesforce.com+001+00B0o00000BGabZ_.

**Comment by rajnikantroy** [comment]
Hi @dyncan,

The code which you have given is apex code.
We cannot execute apex code as we have developed Simplified using **JavaScript and Angular JS** only.

Please follow given link to see how we are querying for any API. https://github.com/rajnikantroy/SalesforceSimplified/blob/master/js/angular/controllers/MenuAndDetailsCtrl.js#L78
