### ISSUE TITLE
When clicked on Renew in Debug log 'Session Expired or Invalid' message

### ISSUE THREAD

**Issue by nileshadkar** [rajnikantroy/SalesforceSimplified#5]
When clicked on Renew in Debug log 'Session Expired or Invalid' message

**Comment by nitishhhkumar** [comment]
Hi @nileshadkar Renew button is from other extension(Salesforce advanced Code searcher)
To fix the issue you will have to contact Sameer N Miraj(sameernmiraj@gmail.com)

Salesforce Simplified give you only My Logs button on debug log page.
